require('../config/db')();

const db = require('../models');

db.User.insertMany([
    {
        email: 'ishtarsink@venus.com',
        password: 'vaultofglass',
        username: 'Atheon',
        firstName: 'Atheon',
        lastName: 'Times-Conflux',
        status: 0,
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: '',
    },
    {
        email: 'oceanofstorms@moon.com',
        password: 'crotasend',
        username: 'Scrota',
        firstName: 'Crota',
        lastName: 'Son-of-Oryx',
        status: 0,
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: '',
    },
    {
        email: 'dreadnaught@saturn.com',
        password: 'kingsfall',
        username: 'Auryx',
        firstName: 'Oryx',
        lastName: 'The-Taken-King',
        status: 0,
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: '',
    },
    {
        email: 'dreadnaught7@saturn.com',
        password: 'kingsfalls',
        username: 'Auryous',
        firstName: 'Oryx-Raid',
        lastName: 'The-King',
        status: 0,
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: '',
    },
    {
        email: 'plaguelands@earth.com',
        password: 'wrathofthemachine',
        username: 'Spider',
        firstName: 'Aksis',
        lastName: 'Archon-Prime',
        status: 0,
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: '',
    },
]);