module.exports = [
    {
        email: 'ishtarsink@venus.com',
        password: '1234',
        username: 'Atheon',
        firstName: 'Atheon',
        lastName: 'Times-Conflux',
        status: 0,
        inboundPendingRooms: [],
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: 'https://i.imgur.com/izGw0wB.jpg',
    },
    {
        email: 'dreadnaught7@saturn.com',
        password: '1234',
        username: 'Auryous',
        firstName: 'Oryx-Raid',
        lastName: 'The-King',
        status: 0,
        inboundPendingRooms: [],
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: 'https://styles.redditmedia.com/t5_2tmtib/styles/profileIcon_pcmjnyopxm851.png?width=256&height=256&crop=256:256,smart&frame=1&s=868d500bf8180ecdc516e2a8fab4f66536a894b0',
    },
    {
        email: 'plaguelands@earth.com',
        password: '1234',
        username: 'Spider',
        firstName: 'Aksis',
        lastName: 'Archon-Prime',
        status: 0,
        inboundPendingRooms: [],
        inboundPendingFriends: [],
        outboundPendingFriends: [],
        friends: [],
        blocked: [],
        imageSrc: 'https://i.pinimg.com/originals/6a/78/f7/6a78f73a95511beb19cb7da69267e956.jpg',
    },
];